apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jsjrdev-poi-map-app-dev
  annotations:
    argocd/app-name: jsjrdev-poi-map-app-dev
    backstage.io/kubernetes-id: jsjrdev-poi-map-app
    backstage.io/kubernetes-namespace: jsjrdev
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/jsjrdev-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/jsjrdev/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/jsjrdev/deployments/jsjrdev-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/jsjrdev-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jsjrdev-poi-map-app-jsjrdev.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jsjrdev"
  system: workshop-system-jsjrdev
  consumesApis:
    - gateway-api-jsjrdev
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jsjrdev
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jsjrdev"
